language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
services:
  - memcached
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-matplotlib
  - sudo apt-get install -y libhdf5-serial-dev
  - sudo apt-get install -y libnetcdf-dev
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database ooi_ui;' -U postgres
  - psql -c 'create database ooi_asset;' -U postgres
  - psql -c 'create database ooi_user_management;' -U postgres
  - psql -U postgres ooi_ui -c "create extension postgis;"
  - psql ooi_ui < db/ooi_ui_schema.sql
  - psql ooi_ui < db/ooi_ui_bulk_load.sql
script:
  - python ooiservices/manage.py test
notifications:
    flowdock: 7728e9be2e099628ea6b3b0f489d2f9c
