status_handler:
    service_mode: demo # demo or live
    wsgi_server:
        url: localhost
        port: 8845
    postgresql_server:
        username: postgres
        password: password
        url: localhost
        port: 5432
        database: test
    uframe_server:
        username: uframe
        password: password
        url: localhost
        port: 1234
    platform:
        required_attributes: ['platform_id']