# Configuration
#
# This represents a top level configuration and can be imported with
#
# from ooiservices.config import DataSource
# children of this configuration are in a dictionary
# db_name = DataSource['DBName']

#Database configuration
DataSource:
    #supported DB:
  DBType: sqlite
  DBName: db/test.db
    #DBType: psql
    #DBName: handlebars
    #user: luke
    #password:
    #host: localhost
    #port: 5432

# Specifies the Model Adaptor to use
# Options include:
#   - SQL
#   - uFrame
#   - Hybrid
Adaptor: SQL

uFrame:
  host:
  port:

