ENV_NAME: 'LOCAL_DEVELOPMENT'

COMMON: &common
    # Logging
    LOGGING: True
    LOG_FILE_PTAH: '/logs/'
    LOG_FILE: 'ooiservices.log'
    # Server config
    DEPLOYMENT_SCENARIO: LOCAL_DEVELOPMENT
    SECRET_KEY: 'ccdf5de08ac74855bda3e7e309d871e5'
    UI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SSL_DISABLE: False
    JSONIFY_PRETTYPRINT_REGULAR: true
    # sql / db config
    SQLALCHEMY_COMMIT_ON_TEARDOWN: True
    SQLALCHEMY_RECORD_QUERIES: True
    OOI_SLOW_DB_QUERY_TIME: 0.5
    WHOOSH_BASE: 'ooiservices/whoosh_index'
    SERVER_DNS: 'localhost'
    HOST: localhost
    PORT: 4000
    # UFrame config
    UFRAME_URL:             'http://localhost:12576'
    UFRAME_ASSETS_URL:      'http://localhost:12573'
    UFRAME_ANNOTATION_URL : 'http://localhost:12580'
    UFRAME_ALERTS_URL:      'http://localhost:12577'
    UFRAME_INST_URL:        'http://localhost:12572'
    UFRAME_ANTELOPE_URL:    'http://localhost:12582/data/list/antelope/'
    UFRAME_MISSIONS_URL:    'http://localhost:8000'
    UFRAME_SUBSCRIBE_URL:   'http://localhost:12585'
    UFRAME_MISSIONS_BASE:   '/missions'
    UFRAME_ANNOTATION_BASE: '/annotations'
    UFRAME_URL_BASE:        '/sensor/inv'
    UFRAME_TOC:             '/sensor/inv/toc'
    UFRAME_INST_BASE:       '/instrument/api'
    UFRAME_PLAT_BASE:       '/platform/api'
    UFRAME_TIMEOUT_CONNECT: 5
    UFRAME_TIMEOUT_READ: 30
    UFRAME_DATA_REQUEST_LIMIT: 2880
    UFRAME_PLOT_TIMEOUT: 60
    DATA_POINTS: 1000
    # redmine
    REDMINE_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    REDMINE_URL: 'https://redmine-asa.ooi.rutgers.edu' #'https://uframe-cm.ooi.rutgers.edu'
    REDMINE_PROJECT_ID: 'ocean-observatory' #'ooi-ui-api-testing'
    # redis
    REDIS_URL: 'redis://localhost:6379'
    # google
    GOOGLE_ANALYTICS_URL: 'https://www.google-analytics.com/collect?v=1&tid=UA-50606390-3&cid=1&t=event'
    # alfresco
    ALFRESCO_CMIS_URL:  'https://alfresco.oceanobservatories.org/alfresco/s/api/cmis'
    ALFRESCO_DL_URL:    'https://alfresco.oceanobservatories.org/alfresco/s/api/node/content/workspace/SpacesStore'
    ALFRESCO_TICKET_URL: 'https://alfresco.oceanobservatories.org/alfresco/s/api/login'
    ALFRESCO_LINK_URL:  'https://alfresco.oceanobservatories.org/alfresco/n/content/workspace/SpacesStore/'
    ALFRESCO_REPO_ID:   'c161bc66-4f7e-4a4f-b5f2-aac9fbf1d3cd'
    ALFRESCO_USERNAME:  'admin'
    ALFRESCO_PASSWORD:  'admin'
    # cilogon
    CILOGON_ID: 'myproxy:oa4mp,2012:/client_id/84e7951a567243a62ae8bc3e13c12c8'
    CILOGON_SECRECT: 'BK2CDBn-FTbYheNs7dz5neKrYKLVcLmd7Ea-ut1Mgzf8c4Bc4NJ2jIi0H6y4vdur17P-4_Hm50d74CyUdXwcDsOF7ds3I9fKjuwVIdYzc37Olu_oCU0xdWW2nJS36WGYiMZ59LtMueVriL4kyUh34YX34g7a8RVu_rPK8Db_vPkN5uIJ_APHbIxTBS6ASoK3N8aRFtkDfxX27Sl2QIQx2RHrd5A8vRh8TLP7rfAlyq6ttjy8Qibqmx35XgWb-ngKy3NyLZM2y8XdiTEBY88r1heFY9ap2A4I6w3IRfoLc4oTjf5weXK9h6yDOthKjBoiR067Ae0GgJXQDyTjbqA4SUee'

DEVELOPMENT: &development
    <<: *common
    DEBUG: True
    SQLALCHEMY_DATABASE_URI: 'postgres://user:password@hostname/database_name'
    SSL_DISABLE: True
    WTF_CSRF_ENABLED: False

LOCAL_DEVELOPMENT: &local_dev
    <<: *common
    DEBUG: True
    SQLALCHEMY_DATABASE_URI: 'postgres://postgres:postgres@localhost/ooiuidev'
    SSL_DISABLE: True
    WTF_CSRF_ENABLED: False
    TOEMAIL: 'name@email.com'

TESTING_CONFIG: &testing
    <<: *common
    TESTING: True
    SQLALCHEMY_DATABASE_URI: 'postgres://postgres:postgres@localhost/ooiuitest'
    WTF_CSRF_ENABLED: False

PRODUCTION: &production
    <<: *common
    SQLALCHEMY_DATABASE_URI: 'postgres://postgres:postgres@localhost/ooiuiprod'
    SSL_DISABLE: False
    WTF_CSRF_ENABLED: True
    TOEMAIL: 'name@email.com'
